version: "3.5"
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:${PORTAINER_VER}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    labels:
      - "traefik.http.routers.portainer.rule=PathPrefix(`/portainer/`)"
      - "traefik.http.routers.portainer.middlewares=https-redirect"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.routers.portainer-secure.rule=PathPrefix(`/portainer/`)"
      - "traefik.http.routers.portainer-secure.middlewares=portainer-stripprefix"
      - "traefik.http.middlewares.portainer-stripprefix.stripprefix.prefixes=/portainer/"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    restart: always
    
  splunk:
    container_name: splunk
    image: splunk/splunk:${SPLUNK_VER}
    ports:
      - 9997:9997
      - 8089:8089
    environment:
      SPLUNK_PASSWORD: 'Changeme1!'
      SPLUNK_START_ARGS: '--accept-license'
      TZ: 'America/Chicago'
      #SPLUNK_UPGRADE: 'true' # Only use when upgrading splunk. Modify SPLUNK_VER in .env to the version you want
    volumes:
      - splunk_etc:/opt/splunk/etc
      - splunk_var:/opt/splunk/var
      - ./web.conf:/opt/splunk/etc/system/local/web.conf
      - ./zeek/zeek-logs/:/logs/zeek-logs/
      - ./quick-fleet/result.log:/logs/osquery/result.log
      - ./quick-fleet/status.log:/logs/osquery/status.log
    labels:
      - "traefik.http.routers.splunk.rule=PathPrefix(`/splunk`)"
      - "traefik.http.routers.splunk.middlewares=https-redirect"
      - "traefik.http.routers.splunk-secure.tls=true"
      - "traefik.http.routers.splunk-secure.rule=PathPrefix(`/splunk`)"
      - "traefik.http.services.splunk.loadbalancer.server.port=8000"
    restart: unless-stopped
    
  jupyter-notebooks:
    container_name: jupyter-notebooks
    image: jupyter/all-spark-notebook:${JUPYTER_VER}
    ports:
      - "8888:8888"
    environment:
      - NB_UID=1001
      - NB_GID=1001
      - JUPYTER_ENABLE_LAB=yes
      - NB_USER=splunk
      - CHOWN_EXTRA=/home/splunk
    volumes:
      - splunk_etc:/home/splunk/etc
      - splunk_var:/home/splunk/var
      - jupyter-notebooks:/home/jovyan
    labels:
      - "traefik.http.routers.jupyter.rule=PathPrefix(`/jupyter`)"
      - "traefik.http.routers.jupyter.middlewares=https-redirect"
      - "traefik.http.routers.jupyter-secure.tls=true"
      - "traefik.http.routers.jupyter-secure.rule=PathPrefix(`/jupyter`)"
      - "traefik.http.services.jupyter.loadbalancer.server.port=8888"
    restart: always
    
  thehive:
    container_name: thehive
    image: thehiveproject/thehive:${HIVE_VER}
    depends_on:
      - elasticsearch
      - cortex
    #command:
    #  - --cortex-port\ 9001
    # ports:
      # - "9000:9000"
    volumes:
      - ./application.conf:/etc/thehive/application.conf
    labels:
      - "traefik.http.routers.thehive.rule=PathPrefix(`/thehive/`)"
      - "traefik.http.routers.thehive.middlewares=https-redirect"
      - "traefik.http.routers.thehive-secure.tls=true"
      - "traefik.http.routers.thehive-secure.rule=PathPrefix(`/thehive/`)"
      - "traefik.http.services.thehive.loadbalancer.server.port=9000"
  cortex:
    container_name: cortex
    image: thehiveproject/cortex:${CORTEX_VER}
    depends_on:
      - elasticsearch
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:${ELASTIC_VER}
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
  
  traefik:
    container_name: traefik
    image: traefik:${TRAEFIK_VER}
    command:
      - --providers.docker=true 
      - --serversTransport.insecureSkipVerify=true
      - --api.dashboard=true # Enable dashboard
      - --entrypoints.web.address=:80
      - --entrypoints.web-secure.address=:443
      # - --api.insecure=true
    ports:
      - "80:80"
      - "443:443"
      # - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=https-redirect"
      - "traefik.http.routers.api-secure.tls=true"
      - "traefik.http.routers.api-secure.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
    restart: always

volumes:
  portainer:
  splunk_etc:
  splunk_var:
  jupyter-notebooks:
  elasticsearch:

